# NumPy
NumPy bietet uns die Möglichkeit sehr performant mit ein- und mehrdimensionalen Arrays umzugehen. Die Quelltexte die wir im Folgenden
verwenden sind meist dem GitHub-Repository von Bressert zu *NUmPy and SciPy* aus dem O\'Reilly-Verlag entnommen.

## Benchmark
Um uns die Vorteile von NumPy klar zu machen vergleichen wir die Anwendung einer Funktion auf eine Liste und die gleiche Anwendung
mit Hilfe eines NumPy-Arrays. Wir verwenden das Modul *timeit*, um Rechenzeiten auf der Konsole auszugeben.
Wenn Sie dieses Notebook nochmals selbst ausführen warten Sie bitte einige Zeit. Die Ausgabe zu NumPy kommt sofort auf der Konsole,
für die Liste benötigen wir deutlich länger.

In [1]:
"""
Example numpy_21_ex1.

The source from GitHub is adapted to PEP8.

Source: Bressert: NumPy and SciPy, O'Reilly.
"""
import timeit
import numpy as np

# Create an array with 10^7 elements.
arr = np.arange(1e7)

# Converting ndarray to list
larr = arr.tolist()


# Lists cannot by default broadcast,
# so a function is coded to emulate
# what an ndarray can do.
def list_times(alist, scalar):
    for i, val in enumerate(alist):
        alist[i] = scalar * val
    return alist


# Number of tries in timeit
N = 10
# NumPy array broadcasting
time1 = timeit.timeit('1.1 * arr', 'from __main__ import arr', number=N)
time1 /= N
print("Average time for NumPy broadcasting: ", time1, 'Sekunden.')

# List and custom function for broadcasting
time2 = timeit.timeit('list_times(larr, 1.1)',
                      'from __main__ import list_times, larr', number=N)
time2 /= N
print("Average time for using a list: ", time2, 'Sekunden.')

print("NumPy gives us an acceleration of factor ", int(time2/time1))

Average time for NumPy broadcasting:  0.019528290000000004 Sekunden.
Average time for using a list:  0.8019384200000002 Sekunden.
NumPy gives us an acceleration of factor  41


## Anlegen von Arrays
Wir zeigen einige Methoden, wie wir NumPy-Arrays erzeugen können. Das reicht von der Verwendung von vorhandenen Daten über eine ganze Reihe von nützlichen Konstrukturen, die wir in NumPy einsetzen können.

In [2]:
# First we create a list and then
# wrap it with the np.array() function.
alist = [1, 2, 3]
arr = np.array(alist)

# Added by Manfred
a_second_list = [[1, 2, 3],
                 [4, 5, 6]]

arr = np.array(a_second_list)
print("Number of rows and columns: ", arr.shape)

# Creating an empty array with given shape
arr = np.empty(shape=(2, 2), dtype=np.float64)
print(arr)
# Creating an array of zeros with five elements
arr = np.zeros(5)
print(arr)
# Creating an array of ones with five elements
arr = np.ones(5)
print(arr)
# Create the identy matrix
arr = np.eye(N=4, dtype=np.float32)
print(arr)
# Create a matrix filled with a given value
arr = np.full(shape=(2, 3), fill_value=2.0)
print(arr)

# What if we want to create an array going from 0 to 100?
arr = np.arange(101)

# Or 10 to 100?
arr = np.arange(10, 101)

# If you want 100 steps from 0 to 1...
arr = np.linspace(0, 1, 100)

# Or if you want to generate an array from 1 to 10
# in log10 space in 10 steps...
arr = np.logspace(start=0.0, stop=1.0, num=10, endpoint=True, base=10.0)
print("An array in logspace ", arr)

# Creating a 5x5 array of zeros (an image)
image = np.zeros((5, 5))

# Creating a 5x5x5 cube of 1's
# The astype() method sets the array with integer elements.
cube = np.zeros((5, 5, 5)).astype(int) + 1

# Or even simpler with 16-bit floating-point precision...
cube = np.ones((5, 5, 5)).astype(np.float16)


# Data typing
# Array of zero integers
arr = np.zeros(2, dtype=int)

# Array of zero floats
arr = np.zeros(2, dtype=np.float32)

# Reshaping
# Creating an array with elements from 0 to 999
arr1d = np.arange(1000)
print(arr1d.shape)

# Now reshaping the array to a 10x10x10 3D array
arr3d = arr1d.reshape((10, 10, 10))

# The reshape command can alternatively be called this way
arr3d = np.reshape(arr1d, (10, 10, 10))

# Inversely, we can flatten arrays
arr4d = np.zeros((10, 10, 10, 10))
arr1d = arr4d.ravel()
print(arr1d.shape)


Number of rows and columns:  (2, 3)
[[1.44635488e-307 1.37962320e-306]
 [1.29060871e-306 1.24611266e-306]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]]
An array in logspace  [ 1.          1.29154967  1.66810054  2.15443469  2.7825594   3.59381366
  4.64158883  5.9948425   7.74263683 10.        ]
(1000,)
(10000,)


## Zugriff auf Elemente eines Arrays

Wir können nicht nur mit Hilfe von Indices auf die Feldelemente zugreifen, was sehr nützlich ist.

In [3]:
"""
Example numpy_213_ex1.

The source from GitHub is adapted to PEP8.

Source: Bressert: NumPy and SciPy, O'Reilly.
"""
alist = [[1, 2], [3, 4]]

# To return the (0,1) element we must index as shown below.
print("alist[0][1] = ", alist[0][1])

# Converting the list defined above into an array
arr = np.array(alist)

# To return the (0,1) element we use ...
print("arr[0, 1] = ", arr[0, 1])

# Now to access the last column, we simply use ...
print("the last column of arr: ", arr[:, 1])

# Accessing the rows is achieved in the same way.
print("the last row of arr: ", arr[1, :])

# Creating an array
arr = np.arange(5)

# Creating the index array
index = np.where(arr > 2)
print("the index array for arr>2: ", index)

# Creating the desired array
new_arr = arr[index]
print("the new array with the index array: ", new_arr)

# We use the previous array
new_arr = np.delete(arr, index)

index = arr > 2
print("the boolean index array for arr>2: ", index)
new_arr = arr[index]
print("the new array with the boolean index array: ", new_arr)

alist[0][1] =  2
arr[0, 1] =  2
the last column of arr:  [2 4]
the last row of arr:  [3 4]
the index array for arr>2:  (array([3, 4], dtype=int64),)
the new array with the index array:  [3 4]
the boolean index array for arr>2:  [False False False  True  True]
the new array with the boolean index array:  [3 4]


Empfehlung nicht nur von Bressert ist bei großen Datenmengen die logische Indizierung einzusetzen.

## Slicing
Slicing kennen Sie eventuell bereits aus anderen Sprachen wie R. Hier einige Beispiele:

In [4]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)
print("arr[:, 1]: ", arr[:, 1])
print("arr[:, 1:]: ", arr[:, 1:])
# in i:j we include i, but not j!
print("arr[:, 0:2]: ", arr[:, 0:2])
print("arr[0, :]: ", arr[0, :])


[[1 2 3]
 [4 5 6]]
arr[:, 1]:  [2 5]
arr[:, 1:]:  [[2 3]
 [5 6]]
arr[:, 0:2]:  [[1 2]
 [4 5]]
arr[0, :]:  [1 2 3]


## Mathematische Funktionen in NumPy
Wir hatten bereits das *math*-Modul für die Wurzel eingesetzt. In NumPy finden wir nochmals alle speziellen Funktionen. 
Im Zweifelsfall verwenden wir immer die Implementierung in NumPy. Der Grund ist höhere Performanz und insbesondere die Möglichkeit,
eine Funktion direkt auf ein komplettes Array anzuwenden.

In [5]:
"""
Example for basic mathematical operations using NumPy arrays.

Code is based on the examples in Wood.

Source: Wood, Python and Matplotlib Essentials for Scientists and Engineers.
"""
# some arrays
a = np.arange(10, 50, 10)
b = np.arange(4)
print("a = ", a)
print("b = ", b)

c = a - b
print("\na-b = ", c)
print("b**2 = ", b**2)
d = 5.0 * np.sqrt(a)
print("5.0 * np.sqrt(a) =", d)
print("inner product np.dot(a, b) = ", np.dot(a, b))

e1 = np.array([1.0, 0.0, 0.0], dtype=np.float64)
e2 = np.array([0.0, 1.0, 0.0], dtype=np.float64)
print("vector product np.cross(e1, e2) = ", np.cross(e1, e2))

# Two-dimensional arrays
a = np.arange(4.0).reshape((2, 2))
print("\nmatrix a =\n", a)
b = a+2
print("\nmatrix b =\n", b)
# elementwise multiplication
c = a*b
print("\nmatrix a*b =\n", c)
# matrix multiplication
c = np.dot(a, b)
print("\nmatrix np.dot(a, b) =\n", c)

# arithmetic
a = np.ones((3, 2))
b = np.arange(6).reshape(3, 2)
print("\nmatrix a =\n", a)
print("matrix b =\n", b)
b += 1
print("result for b += 1 = \n", b)
c = a
c += 3.0*a
print("matrix a += 3.0*a =\n", c)

# functions on arrays
print("\nb.min() = ", b.min())
print("b.max() = ", b.max())
print("b.sum() = ", b.sum())


a =  [10 20 30 40]
b =  [0 1 2 3]

a-b =  [10 19 28 37]
b**2 =  [0 1 4 9]
5.0 * np.sqrt(a) = [15.8113883  22.36067977 27.38612788 31.6227766 ]
inner product np.dot(a, b) =  200
vector product np.cross(e1, e2) =  [0. 0. 1.]

matrix a =
 [[0. 1.]
 [2. 3.]]

matrix b =
 [[2. 3.]
 [4. 5.]]

matrix a*b =
 [[ 0.  3.]
 [ 8. 15.]]

matrix np.dot(a, b) =
 [[ 4.  5.]
 [16. 21.]]

matrix a =
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
matrix b =
 [[0 1]
 [2 3]
 [4 5]]
result for b += 1 = 
 [[1 2]
 [3 4]
 [5 6]]
matrix a += 3.0*a =
 [[4. 4.]
 [4. 4.]
 [4. 4.]]

b.min() =  1
b.max() =  6
b.sum() =  21
